### ISSUE TITLE
Detects ATLauncher Packs

### ISSUE THREAD

**Issue by tattyseal** [OpenLauncher/OpenLauncher#6]
"Your" launcher detects ATLauncher packs that are in the same folder. You should IMO add something to distinguish your packs from AT's so it doesn't show then as it won't update/run them properly.

**Comment by modmuss50** [comment]
This version only has critical bug fixes, we are working on a full rewrite of the launcher here:
https://github.com/OpenLauncher/OpenLauncher-StandAlone

I will leave this open in case it becomes a major issue.

Thank you for your feed back :+1:

**Comment by modmuss50** [comment]
I dont know why you would run it in the same folder? It is the same launcher so it would need a PR into the atl one any way.

**Comment by tattyseal** [comment]
:-1:

**Comment by modmuss50** [comment]
I don't see a lot of point in fixing it the issue.

**Comment by modmuss50** [comment]
This may have been fixed with https://github.com/ATLauncher/ATLauncher/pull/159

I may release an update if required.
